name: "All Contributors"
on:
   issue_comment:
     types: [created]
permissions:
   contents: write
   issues: write 
   pull-requests: write
  
jobs:
  all-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: all-contributors/all-contributors-action@v0.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
