
name: "All Contributors"

on:
   issue_comment:
     types: [created] 
  
jobs:
  all-contributors:
    runs-on: ubuntu-latest
    
    steps:
      - name: Runs All Contributers Bot
        uses: wow-actions/all-contributors-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
      
      
           
